export {default as Footer} from './Footer/Footer'
export {default as Header} from './Header/Header'
export {default as LastProducts} from './LastProducts/LastProducts'
export {default as Nav} from './Nav/Nav'
export {default as QuickLinks} from './QuickLinks/QuickLinks'
export {default as Slider} from './Slider/Slider'
